### ISSUE TITLE
Considerações Seminário Final

### ISSUE THREAD

**Issue by gladimircc** [MatheusVictoria/Sistema-Gerenciador-de-Associacoes-Esportivas---TCC---Fatec-Pelotas#1]
- [x] Corrigir o cabeçalho do relatório. "Lista de Centro de **Trinamentos**"
Na tabela **mensalidade**
- [x] Renomear campo **data** para **data pagamento**
- [x] Criar campo **valor pago**

**Comment by MatheusVictoria** [comment]
Corrigido cabeçalho da pagina Lista de Centro de Treinamentos.
Alterado campo data para data_pagamento na tabela de mensalidade.
Criado campo valor_pago na tabela de mensalidade.
