### ISSUE TITLE
Seminário Final TCC I

### ISSUE THREAD

**Issue by edeciofernando** [MatheusVictoria/Sistema-Gerenciador-de-Associacoes-Esportivas---TCC---Fatec-Pelotas#2]
Tarefas:
- [ ] Melhorar descrição do objetivo geral
- [ ] Cuidados Gramaticais: pratica, especifico, Analise, pagina, recebera, ocorrencia, Codigniter...
- [ ] Cuidados Gramaticais: Conforme vemos na Figura 2, temos... 
- [ ] Abreviaturas: primeiro uso descrever - CI (CodeIgniter), API...
- [ ] Controle de Pagtos? Data Pgto? No BD, não contempla
- [ ] Da Fig.1 pula para Fig. 5
- [ ] Cuidar tempo da apresentação

Dúvidas:
* Pode citar o nome da Associação?

**Comment by MatheusVictoria** [comment]
Feito as correções solicitadas.
